package calcul;


/**
* calcul/calcul_montants.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./spec.idl
* Tuesday, 7 December 2021 18:07:18 o'clock WAT
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
